export type DomainErrorCode =
  | "AUTHORITY_EXPANSION"
  | "APPROVAL_ACTOR_REJECTED"
  | "APPROVAL_DIGEST_MISMATCH"
  | "APPROVAL_EDITED"
  | "APPROVAL_FORMAT_INVALID"
  | "APPROVAL_MISSING"
  | "BASE_DRIFT"
  | "CONTRADICTORY_STATE_LABELS"
  | "DUPLICATE_YAML_KEY"
  | "GITHUB_AUTH_UNAVAILABLE"
  | "INTERNAL_ERROR"
  | "INCOMPLETE_ISSUE"
  | "ISSUE_AUTHOR_REJECTED"
  | "INVALID_CONTRACT"
  | "INVALID_CONTRACT_BLOCK_COUNT"
  | "INVALID_JSON"
  | "INVALID_POLICY"
  | "INVALID_QUEUE_PLAN_INPUT"
  | "INVALID_RESULT_MANIFEST"
  | "INVALID_RESULT_REVIEW"
  | "INVALID_SIMULATION"
  | "INVALID_TRANSITION"
  | "INVALID_YAML"
  | "POLICY_DISABLED"
  | "POLICY_DRIFT"
  | "RESULT_TOO_LARGE"
  | "RECOVERY_ROOT_CONTRADICTORY"
  | "RECOVERY_ROOT_MISSING"
  | "SIMULATION_FILE_ERROR"
  | "TERMINAL_STATE"
  | "UNTRUSTED_REPOSITORY"
  | "WORK_ID_CONFLICT"
  | "YAML_ALIAS_FORBIDDEN"
  | "YAML_TAG_FORBIDDEN";

export class DomainError extends Error {
  constructor(readonly code: DomainErrorCode, message: string) {
    super(`${code}: ${message}`);
  }
}
